// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: fluxer/AnalisadorLexico.jflex

/*
 * ======================================================================================
 * Seção 1: Código de Usuário
 * ======================================================================================
 * Esta é a primeira seção de um arquivo de especificação JFlex.
 * Todo o código Java escrito aqui é copiado literalmente para o início do arquivo .java
 * que será gerado pelo JFlex. É o local ideal para declarações de pacote,
 * importações de bibliotecas e definição de classes auxiliares que o analisador possa precisar.
 *
 * Versão Corrigida: Lógica de String refeita e Comentários de Bloco simplificados.
 */

// Define o pacote (namespace) ao qual a classe do analisador pertencerá.
// Isso é fundamental para a organização do projeto e para permitir que o analisador
// acesse outras classes do mesmo pacote, como 'TokenLexico' e 'TipoToken'.

package fluxer;

// A diretiva '%%' é um separador obrigatório entre as seções do arquivo .jflex.

@SuppressWarnings("fallthrough")
public class FluxerLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int BLOCO_COMENTARIO = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\2\0\1\10\2\0\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\10\23"+
    "\1\24\1\0\1\25\1\26\1\27\2\0\1\30\1\31"+
    "\2\30\1\32\1\30\21\33\1\34\2\33\1\35\1\36"+
    "\1\37\1\10\1\33\1\0\1\40\1\31\1\41\1\42"+
    "\1\43\1\44\1\45\1\33\1\46\2\33\1\47\1\50"+
    "\1\51\1\52\1\53\1\33\1\54\1\55\1\56\1\57"+
    "\1\60\1\33\1\34\2\33\1\61\1\0\1\62\7\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\4\1\7\1\4\1\1\2\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\2\14\1\17\7\14\1\20\1\21"+
    "\1\22\2\23\1\24\1\0\3\25\1\12\1\26\1\13"+
    "\1\27\1\30\1\31\3\0\2\14\1\32\5\14\1\17"+
    "\2\14\1\33\2\14\1\34\1\35\1\10\1\0\1\31"+
    "\1\10\20\14\1\36\1\37\5\14\1\40\1\41\1\14"+
    "\1\42\1\43\1\44\2\14\1\45\1\46\10\14\1\47"+
    "\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\231\0\231"+
    "\0\u0132\0\231\0\u0165\0\231\0\u0198\0\u01cb\0\u01fe\0\u0231"+
    "\0\231\0\377\0\377\0\u0264\0\231\0\231\0\u0297\0\u02ca"+
    "\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc\0\u042f\0\u0462"+
    "\0\231\0\231\0\u0495\0\231\0\u04c8\0\231\0\u04fb\0\231"+
    "\0\u052e\0\u0561\0\231\0\231\0\231\0\u0594\0\231\0\u05c7"+
    "\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\u0264\0\u06f9\0\u072c"+
    "\0\u075f\0\u0792\0\u07c5\0\u0264\0\u07f8\0\u082b\0\u085e\0\u0891"+
    "\0\u08c4\0\231\0\231\0\u05fa\0\u08f7\0\u08f7\0\u0660\0\u092a"+
    "\0\u095d\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f\0\u0ac2"+
    "\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1\0\u0bf4\0\u0c27\0\u0264"+
    "\0\u0264\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\u0264\0\u0264"+
    "\0\u0d59\0\u0264\0\u0264\0\u0264\0\u0d8c\0\u0dbf\0\u0264\0\u0264"+
    "\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57"+
    "\0\u0264\0\u0264";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\0\2\5\1\6\1\7\1\10\1\11"+
    "\1\12\2\13\1\14\1\15\1\16\1\13\1\17\2\20"+
    "\1\21\1\22\1\23\1\22\5\24\1\25\1\4\1\26"+
    "\1\27\1\30\1\24\1\31\1\32\4\24\1\33\1\34"+
    "\1\35\1\24\1\36\1\37\1\24\1\40\1\41\1\42"+
    "\2\43\1\44\2\43\1\45\1\43\1\46\26\43\1\47"+
    "\24\43\3\50\2\0\1\51\5\50\1\52\47\50\64\0"+
    "\2\5\1\0\2\5\103\0\1\53\47\0\1\54\75\0"+
    "\1\55\52\0\1\56\7\0\1\55\1\57\54\0\3\60"+
    "\56\0\1\60\1\0\3\20\5\0\1\61\1\62\1\0"+
    "\1\63\6\0\1\62\36\0\1\60\1\0\3\20\6\0"+
    "\1\62\10\0\1\62\40\0\3\24\4\0\5\24\3\0"+
    "\21\24\23\0\3\24\4\0\5\24\3\0\5\24\1\64"+
    "\13\24\23\0\3\24\4\0\5\24\3\0\12\24\1\65"+
    "\6\24\23\0\3\24\4\0\5\24\3\0\10\24\1\66"+
    "\10\24\23\0\3\24\4\0\5\24\3\0\1\67\5\24"+
    "\1\70\3\24\1\71\6\24\23\0\3\24\4\0\5\24"+
    "\3\0\1\72\16\24\1\73\1\24\23\0\3\24\4\0"+
    "\5\24\3\0\17\24\1\74\1\24\23\0\3\24\4\0"+
    "\5\24\3\0\1\75\20\24\23\0\3\24\4\0\5\24"+
    "\3\0\1\76\2\24\1\77\15\24\23\0\3\24\4\0"+
    "\5\24\3\0\14\24\1\100\4\24\23\0\3\24\4\0"+
    "\5\24\3\0\3\24\1\101\15\24\2\0\2\43\1\0"+
    "\2\43\1\0\1\43\1\0\26\43\1\0\24\43\2\0"+
    "\1\44\67\0\1\102\26\0\1\102\12\0\1\102\4\0"+
    "\1\102\6\0\1\50\72\0\1\103\50\0\2\56\4\0"+
    "\55\56\21\0\3\60\6\0\1\62\10\0\1\62\40\0"+
    "\2\104\54\0\1\105\1\0\1\105\2\0\3\106\60\0"+
    "\3\107\4\0\3\107\5\0\5\107\37\0\3\24\4\0"+
    "\5\24\3\0\14\24\1\110\4\24\23\0\3\24\4\0"+
    "\5\24\3\0\11\24\1\111\7\24\23\0\3\24\4\0"+
    "\5\24\3\0\7\24\1\112\11\24\23\0\3\24\4\0"+
    "\5\24\3\0\7\24\1\113\11\24\23\0\3\24\4\0"+
    "\5\24\3\0\11\24\1\114\7\24\23\0\3\24\4\0"+
    "\5\24\3\0\12\24\1\74\6\24\23\0\3\24\4\0"+
    "\5\24\3\0\7\24\1\115\11\24\23\0\3\24\4\0"+
    "\5\24\3\0\14\24\1\116\4\24\23\0\3\24\4\0"+
    "\5\24\3\0\6\24\1\117\12\24\23\0\3\24\4\0"+
    "\5\24\3\0\11\24\1\120\7\24\23\0\3\24\4\0"+
    "\5\24\3\0\1\121\20\24\23\0\3\24\4\0\5\24"+
    "\3\0\14\24\1\122\4\24\23\0\3\106\60\0\3\24"+
    "\4\0\5\24\3\0\3\24\1\123\15\24\23\0\3\24"+
    "\4\0\5\24\3\0\15\24\1\124\3\24\23\0\3\24"+
    "\4\0\5\24\3\0\15\24\1\125\3\24\23\0\3\24"+
    "\4\0\5\24\3\0\16\24\1\126\2\24\23\0\3\24"+
    "\4\0\5\24\3\0\16\24\1\127\2\24\23\0\3\24"+
    "\4\0\5\24\3\0\12\24\1\130\6\24\23\0\3\24"+
    "\4\0\5\24\3\0\1\131\20\24\23\0\3\24\4\0"+
    "\5\24\3\0\2\24\1\132\16\24\23\0\3\24\4\0"+
    "\5\24\3\0\1\133\20\24\23\0\3\24\4\0\5\24"+
    "\3\0\11\24\1\134\7\24\23\0\3\24\4\0\5\24"+
    "\3\0\2\24\1\135\16\24\23\0\3\24\4\0\5\24"+
    "\3\0\5\24\1\136\13\24\23\0\3\24\4\0\5\24"+
    "\3\0\16\24\1\137\2\24\23\0\3\24\4\0\5\24"+
    "\3\0\12\24\1\140\6\24\23\0\3\24\4\0\5\24"+
    "\3\0\14\24\1\141\4\24\23\0\3\24\4\0\5\24"+
    "\3\0\3\24\1\142\15\24\23\0\3\24\4\0\5\24"+
    "\3\0\1\143\20\24\23\0\3\24\4\0\5\24\3\0"+
    "\12\24\1\144\6\24\23\0\3\24\4\0\5\24\3\0"+
    "\15\24\1\145\3\24\23\0\3\24\4\0\5\24\3\0"+
    "\1\146\20\24\23\0\3\24\4\0\5\24\3\0\1\147"+
    "\20\24\23\0\3\24\4\0\5\24\3\0\12\24\1\150"+
    "\6\24\23\0\3\24\4\0\5\24\3\0\4\24\1\151"+
    "\14\24\23\0\3\24\4\0\5\24\3\0\2\24\1\152"+
    "\16\24\23\0\3\24\4\0\5\24\3\0\12\24\1\153"+
    "\6\24\23\0\3\24\4\0\5\24\3\0\3\24\1\154"+
    "\15\24\23\0\3\24\4\0\5\24\3\0\14\24\1\155"+
    "\4\24\23\0\3\24\4\0\5\24\3\0\6\24\1\156"+
    "\12\24\23\0\3\24\4\0\5\24\3\0\10\24\1\157"+
    "\10\24\23\0\3\24\4\0\5\24\3\0\14\24\1\160"+
    "\4\24\23\0\3\24\4\0\5\24\3\0\1\161\20\24"+
    "\23\0\3\24\4\0\5\24\3\0\12\24\1\162\6\24"+
    "\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3978];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\2\11\1\1\1\11\1\1\1\11"+
    "\4\1\1\11\3\1\2\11\12\1\2\11\1\1\1\11"+
    "\1\1\1\11\1\0\1\11\2\1\3\11\1\1\1\11"+
    "\1\1\3\0\16\1\2\11\1\1\1\0\55\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    // Um StringBuilder é usado como um buffer para construir eficientemente o conteúdo
    // de uma string, pedaço por pedaço, conforme ela é lida do arquivo de entrada.
    private StringBuilder stringContent = new StringBuilder();

    // Variáveis para armazenar a linha e a coluna onde uma string começa.
    // Isso é necessário porque o token só é criado no final da string, mas sua
    // posição correta é a do início.
    private int stringStartLine;
    private int stringStartColumn;

    // O contador de aninhamento de comentários que existia antes foi REMOVIDO
    // para simplificar a lógica, conforme solicitado.


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FluxerLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public TokenLexico yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case STRING: {
              System.err.println("ERRO: String não terminada no final do arquivo.");
        yybegin(YYINITIAL); // Retorna ao estado inicial para evitar problemas.
        // Retorna um token de erro para sinalizar o problema.
        return new TokenLexico(TipoToken.ERRO, "String não terminada", stringStartLine, stringStartColumn);
            }  // fall though
            case 115: break;
            case BLOCO_COMENTARIO: {
              System.err.println("ERRO: Bloco de comentário não terminado no final do arquivo.");
        yybegin(YYINITIAL);
            }  // fall though
            case 116: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new TokenLexico(TipoToken.ERRO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 41: break;
          case 2:
            { /* Ação vazia, simplesmente ignora */
            }
          // fall through
          case 42: break;
          case 3:
            { // 1. Limpa o buffer de qualquer conteúdo de string anterior.
                                              stringContent.setLength(0);
                                              // 2. Salva a linha e coluna atuais como a posição de início da string.
                                              stringStartLine = yyline;
                                              stringStartColumn = yycolumn;
                                              // 3. Muda o estado do analisador para STRING, ativando as regras daquele estado.
                                              yybegin(STRING);
            }
          // fall through
          case 43: break;
          case 4:
            { return new TokenLexico(TipoToken.OP_ARITMETICO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 44: break;
          case 5:
            { return new TokenLexico(TipoToken.PARENTESES_ESQ, yytext(), yyline, yycolumn);
            }
          // fall through
          case 45: break;
          case 6:
            { return new TokenLexico(TipoToken.PARENTESES_DIR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 46: break;
          case 7:
            { return new TokenLexico(TipoToken.VIRGULA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 47: break;
          case 8:
            { return new TokenLexico(TipoToken.NUMERO_INT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 48: break;
          case 9:
            { return new TokenLexico(TipoToken.DOIS_PONTOS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 49: break;
          case 10:
            { return new TokenLexico(TipoToken.OP_RELACIONAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 50: break;
          case 11:
            { return new TokenLexico(TipoToken.OP_ATRIBUICAO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 51: break;
          case 12:
            { return new TokenLexico(TipoToken.IDENTIFICADOR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 52: break;
          case 13:
            { return new TokenLexico(TipoToken.COLCHETES_ESQ, yytext(), yyline, yycolumn);
            }
          // fall through
          case 53: break;
          case 14:
            { return new TokenLexico(TipoToken.COLCHETES_DIR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 54: break;
          case 15:
            { return new TokenLexico(TipoToken.OP_LOGICO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 55: break;
          case 16:
            { return new TokenLexico(TipoToken.CHAVES_ESQ, yytext(), yyline, yycolumn);
            }
          // fall through
          case 56: break;
          case 17:
            { return new TokenLexico(TipoToken.CHAVES_DIR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 57: break;
          case 18:
            { stringContent.append(yytext()); // Adiciona o texto encontrado diretamente ao buffer.
            }
          // fall through
          case 58: break;
          case 19:
            { stringContent.append(yytext()); // Adiciona a própria quebra de linha ao buffer.
            }
          // fall through
          case 59: break;
          case 20:
            { yybegin(YYINITIAL); // Volta para o estado normal de análise.
        // Retorna um token de STRING, usando o CONTEÚDO ACUMULADO no StringBuilder
        // e a POSIÇÃO INICIAL que foi salva quando a string começou.
        return new TokenLexico(TipoToken.STRING, stringContent.toString(), stringStartLine, stringStartColumn);
            }
          // fall through
          case 60: break;
          case 21:
            { /* Ação vazia, apenas consome e ignora o conteúdo do comentário */
            }
          // fall through
          case 61: break;
          case 22:
            { yybegin(BLOCO_COMENTARIO);
            }
          // fall through
          case 62: break;
          case 23:
            { /* Comentário de linha: ignora o resto da linha */
            }
          // fall through
          case 63: break;
          case 24:
            { return new TokenLexico(TipoToken.OP_PIPELINE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 64: break;
          case 25:
            { return new TokenLexico(TipoToken.NUMERO_FLOAT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 65: break;
          case 26:
            { return new TokenLexico(TipoToken.EM, yytext(), yyline, yycolumn);
            }
          // fall through
          case 66: break;
          case 27:
            { return new TokenLexico(TipoToken.SE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 67: break;
          case 28:
            { // Usa um switch para "traduzir" a sequência de escape para o caractere real
        // e o adiciona ao buffer da string.
        switch (yytext().charAt(1)) {
            case 'n': stringContent.append('\n'); break;         // \n -> nova linha
            case 't': stringContent.append('\t'); break;         // \t -> tabulação
            case '"': stringContent.append('"'); break;         // \" -> aspas duplas
            case '\\': stringContent.append('\\'); break;        // \\ -> barra invertida
        }
            }
          // fall through
          case 68: break;
          case 29:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 69: break;
          case 30:
            { return new TokenLexico(TipoToken.NULO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 70: break;
          case 31:
            { return new TokenLexico(TipoToken.PARA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 71: break;
          case 32:
            { return new TokenLexico(TipoToken.CONST, yytext(), yyline, yycolumn);
            }
          // fall through
          case 72: break;
          case 33:
            { return new TokenLexico(TipoToken.FALSO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 73: break;
          case 34:
            { return new TokenLexico(TipoToken.FONTE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 74: break;
          case 35:
            { return new TokenLexico(TipoToken.SAIDA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 75: break;
          case 36:
            { return new TokenLexico(TipoToken.SENAO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 76: break;
          case 37:
            { return new TokenLexico(TipoToken.AGREGA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 77: break;
          case 38:
            { return new TokenLexico(TipoToken.FILTRO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 78: break;
          case 39:
            { return new TokenLexico(TipoToken.TRANSFORMA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 79: break;
          case 40:
            { return new TokenLexico(TipoToken.VERDADEIRO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
